### ISSUE TITLE
Transfer copyright to Mozilla?

### ISSUE THREAD

**Issue by jwhitlock** [schalkneethling/bob#1]
Would you be willing to transfer the copyright of this project to Mozilla?

**Comment by schalkneethling** [comment]
Indeed.

**Comment by schalkneethling** [comment]
@jwhitlock Does that mean I need to change the license from MIT to MPL-2?

**Comment by jwhitlock** [comment]
I think MIT is OK, as an accepted open source license. I tend to default to MPL-2 for Mozilla work projects, but it is probably best suited for Firefox and related tech, due to the trademark clauses. I use MIT or BSD for non-Mozilla stuff, they are fine (except BSD does seem to require a copyright statement in each file 🤢 ).

**Comment by schalkneethling** [comment]
@jwhitlock Ok, this one should be ready to transfer to MDN

**Comment by jwhitlock** [comment]
Looks good, thanks @schalkneethling!
